### ISSUE TITLE
Details of the scene manipulation module.

### ISSUE THREAD

**Issue by OliviaZhang1996** [rahul-goel/isrf_code#4]
Hi, Rahul.
This is an excellent and useful work. You have mentioned in the Sec.5.2 that your method can achieve Nerf editing like object translation and scene composition. However, I didn't find related code in your released version. 
Could you tell me the location of the scene manipulation module in your code?
Thanks very much.

**Comment by rahul-goel** [comment]
Hi. Thank you for taking interest in our work.

I have released the code only for segmentation. I did not release the code for object translation and scene composition since I had implemented it in a very hacky manner on top of the original DVGOv2 repository. Making it release ready would take quite some time which I unfortunately don't have at the moment.

However, I can share the core snippet over here. Hopefully it will help. In the `forward` function, the `rgb` values are accumulated as follows:
```py
            bg_over_fg = (bg_alpha.unsqueeze(-1) > fg_alpha.unsqueeze(-1)).float()
            rgb_marched = segment_coo(
                    src=(weights.unsqueeze(-1) * (bg_over_fg * rgb + (1.0 - bg_over_fg) * fg_rgb)),
                    index=ray_id,
                    out=torch.zeros([N, 3]),
                    reduce='sum')
```
The `bg_alpha` and `fg_alpha` are `alpha` values for the background and foreground scenes. The calculation of these values is unchanged. It is done independently as if they are different scenes. The term `weights` is calculated by passing the sum of both the `alpha` terms.

This should give you the correct result but the rendering may be slow. You can speed it up by applying the voxel pruning techniques provided by DVGOv2 on both the scenes instead of one.

**Comment by rahul-goel** [comment]
Let me know if this is not sufficient to understand. Else, I'll put the entire hacky forward function snippet here which you can go through.
